# Site/SEO settings
email: dill@live.cn
baseurl: ""
permalink: /:year/:month/:day/:title/
google_analytics: UA-156587096-1

name: Zen Chan
title: 七.SPACE
description: >
   In the Right Place At the Right Time
url: https://七.space
twitter_username: zenimchan
default_img: /assets/images/seo.jpg
social:
  - name: flickr
    url: https://www.flickr.com/photos/dillchan/
  - name: instagram
    url: https://www.instagram.com/zenimchan/
  - name: 500px
    url: https://500px.com/zenimchan/
  - name: github
    url: https://github.com/ifallchan/
# - name: wechat
#   url: ifallchan

# Contact settings
contact_img: /assets/images/contact.jpg
formcarry: https://formcarry.com/s/gH9CHKYkJyJ

# Disqus settings
disqus: 7space

# MailChimp settings
mailchimp_action: https://space.us4.list-manage.com/subscribe/post-json?u=4e7ce722e4ad9f7a2298a1673&amp;id=0096ef4f6b
mailchimp_input: b_4e7ce722e4ad9f7a2298a1673_0096ef4f6b

# Author settings
author:
  - name: Zen Chan
    bio: the Right Guy
    url: https://七.space

# Pagination settings
pagination:
  enabled: true
  debug: false
  per_page: 7
  permalink: '/page/:num/'
  title: ':title'
  limit: 0
  sort_field: 'date'
  sort_reverse: true
autopages:
  enabled: true
  categories:
    enabled: false
  collections:
    enabled: false
  tags:
    layouts:
      - 'tag.html'
    title: '七.SPACE'
    permalink: '/tag/:tag'
    slugify:
      mode: raw
      cased: true

# Build settings
markdown: kramdown
plugins:
  - jekyll-paginate-v2
  - jekyll-sitemap
compress_html:
    clippings: all
    comments: all
    startings: [html, head, body]
exclude:
  - node_modules
  - .DS_Store
  - barber.jpg
  - Gemfile
  - Gemfile.lock
  - gulpfile.js
  - package.json
  - README.md
